### ISSUE TITLE
Broken in 1.6.1

### ISSUE THREAD

**Issue by Kenira** [Starwaster/RealActiveRadiators#3]
Mods i am running: RO suite with RP1 and Principia.

Basic issue: when timewarping, radiators explode with ridiculously high temperatures (1E6 K and more). Sometimes they will also draw several MW of power (haven't found a way to replicate this yet, maybe just related to the other issue?).

How i tested this: I took a Tank-IV HP with liquid hydrogen. Slapped a radiator and avionics on and then tested it in space (KRASH) with infinite electricity cheat on. Enable radiator, activate max timewarp, wait if things haven't immediately exploded already (sometimes things also explode when you reduce timewarp again). All in sandbox mode.

I have tried the stock radiators, Coatl aerospace radiators, and the one radiator part from RAA itself (i checked in the MM cache and all had ModuleRealActiveRadiator).

I've spent a few hours testing things, and i have a suspicion for what's going on: While timewarping, the tank temperature will slowly increase, until it's so high that the radiator activates itself. At that point, probably something with the large time step from timewarping happens and it overshoots or something (if by chance the radiator doesn't explode when that happens, the tank temperature does make big jumps). It would also explain why in my career save, with lots of things going on and performance being worse / time steps larger, things exploded much earlier compared to sandbox (immediately after hitting timewarp, even just x10).

Also: All the stock radiators didn't cool at all, only the RAA and Coatl radiators provided cooling.

Cheers

EDIT: Forgot that sometimes things only explode if you go back down from max timewarp.

**Comment by Starwaster** [comment]
Needs logs and ModuleManager.ConfigCache file

**Comment by Kenira** [comment]
[logs.zip](https://github.com/Starwaster/RealActiveRadiators/files/3703423/logs.zip)

**Comment by Kenira** [comment]
[debug_KSP_log.zip](https://github.com/Starwaster/RealActiveRadiators/files/3703565/debug_KSP_log.zip)

**Comment by Starwaster** [comment]
I can only reproduce the exploding of the radiator that the mod comes with (the one that tapers toward the end) and that's probably because of poor part thermal characteristics. I can fix that in the part config easily enough.

Other radiators however I have not seen explode no matter how abusive I got with the timewarping

**Comment by Starwaster** [comment]
Copy this to a config file in your GameData folder. (you can delete that file after the mod is updated but it's probably best to avoid that part for now)
```
@PART[RealFuels.radiator1]:FINAL
{
	@mass = 1
	%heatConductivity = 0.001
	%skinInternalConductionMult = 2000
	%radiatorHeadRoom = 0.28
}
```

**Comment by Starwaster** [comment]
regarding power draw, it's only an issue in that refrigeration of that magnitude would  be more massive and currently you're only having to deal with the mass of a radiator. Eventually I plan to make the refrigeration portion configurable where the player can decide how much cooling the tank will have when designing the craft. (being assessed appropriate cost and mass)

But right now, each radiator has a capped cooling cost which is measured in kilowatts for each radiator. You are probably NOT seeing megawatts of power draw. No single radiator in your installation goes that high. What you're probably seeing is the _energy_ transfer over time at high warp. That's measured in joules not watts. At very high warp rates, it's quite likely you _are_ seeing megajoules worth of energy.

**Comment by Kenira** [comment]
I'm relatively sure it was in real time, and it used up my EC storage which was several 10k EC in a matter of seconds, but i don't have a video to prove it.

Also, is it supposed to be heatConductivity in the patch? When i look at the game files i only see a heatConduction variable.

Either way, i just tried it, and while it worked better at low time warp, still same issues as before at high timewarp. Explosions, negative numbers.

Also, are they supposed to draw 40kW? The description says 125W.

**Comment by Starwaster** [comment]
heatConductivity is correct. heatConduction was wrong which is why it got patched.

125W would be the base pump cost and does not take into account cryocooler cost which kicks in any time the thing you are cooling is cooler than the radiators. Remember heat always flows from hot to cold unless work is performed to move the heat. You've been spoiled by stock radiators which provided enormous amounts of cooling basically for free.

Cooling things down to 20K is a lot more expensive than cooling your house or refrigerating your food. Once it is cooled down though, the cryocoolers only have to intercept the heat going through the insulation. If you add enough layers you can keep the heat down to hundreds or even tens of watts. Keeping it in a fairing during launch will also help keep it cool until you get to orbit. (MLI works better in vacuum)
